import type { NextPage } from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";

const Home: NextPage<{ example: any }> = ({ example }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>T3</h1>
        {JSON.stringify(example)}
      </main>
    </>
  );
};

export const getStaticProps = async () => {
  const example = await prisma.example.findMany()
  return {
    props: {
      example
    }
  }
}

export default Home;
